'use client';

import { useEffect, useState } from 'react';
import { useRouter, usePathname } from 'next/navigation';

export default function AuthGuard({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  const pathname = usePathname();
  const [isAuthorized, setIsAuthorized] = useState(false);

  useEffect(() => {
    // Check for the JWT token generated by FastAPI
    const token = localStorage.getItem('admin_token');
    
    // If no token exists and they are not on the login page, boot them out
    if (!token && pathname !== '/') {
      router.replace('/');
    } else {
      // Allow rendering
      setIsAuthorized(true);
    }
  }, [pathname, router]);

  // Prevent UI flashing while checking authentication
  if (!isAuthorized && pathname !== '/') {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  return <>{children}</>;
}